### ISSUE TITLE
error message "0008 no capcha found"

### ISSUE THREAD

**Issue by sickboy2711** [DarkminecrafterHD/freebitco.in-Bot#6]
If I run the script I get then but the error message "0008 no capcha found" please help

**Comment by DarkminecrafterHD** [comment]
The script is outdated
I will try to update it when I can
freebitcoin has changed a lot since the last time I updated
and when i got the script updated they changed another time so i didn't push the changes

As of now, you can only do it manually

**Comment by sickboy2711** [comment]
can you tell when you update the script?
Would be really cool of you

**Comment by DarkminecrafterHD** [comment]
I will update this issue when done

**Comment by sickboy2711** [comment]
hast du noch andere autorollscripts von anderen faucets?

**Comment by DarkminecrafterHD** [comment]
I think that's german...
it translates to: "do you have other autorollscripts from other faucets?"

And no, as of now
only this and freedogecoin, but that one is obsolete too

**Comment by sickboy2711** [comment]
ok thx and good night

**Comment by DarkminecrafterHD** [comment]
I updated the script

can you try it and give feedback?

**Comment by sickboy2711** [comment]
login works fine but for roll i get the same message"0008 no capcha found"

**Comment by sickboy2711** [comment]
I think I have found the error.
The download works already times but in the step "TAG POS=1 TYPE=INPUT ATTR=NAME:file-upload-01 CONTENT={{path}}{{file}}" this is not used

**Comment by sickboy2711** [comment]
I think I have found the error.
he download works, the captcha is also solved but not used

**Comment by sickboy2711** [comment]
i have fill in " TAG POS=1 TYPE=INPUT:TEXT ATTR=* CONTENT={{Answer}}" instead of this "TAG POS=1 TYPE=INPUT ATTR=ID:adcopy_response CONTENT={{Answer}}"
No the1. run works fine

**Comment by DarkminecrafterHD** [comment]
ohh my
i completly forgot about the answer textbox
Sorry
i'll fix it now

thanks

**Comment by sickboy2711** [comment]
no problem. If you can still adjust the size of the selected Capcha was perfect. currently is the whole picture (with input field and solution field) sent what at 9kw.eu as overgrosses picture counts. only the captcha would be billed as Standart

**Comment by DarkminecrafterHD** [comment]
Ohh for that you just need to go to the `'Save captcha image'` section and coment the line that sais `'whole captcha frame` and uncomment the `'only captcha image` one

**Comment by DarkminecrafterHD** [comment]
I updated the captcha insert code
and the 9kw feedback code

**Comment by sickboy2711** [comment]
ok i can check it in 30 minutes. I`ll give feedback.
can i use this script for Doge to?

**Comment by DarkminecrafterHD** [comment]
No Doge use a diferent process
In the testing branch there is some old code for that purpose, but it may not work now

but as of now my freedogecoin accountis banned so i didn't bother on updating it

I may update it some day if i got the time

**Comment by sickboy2711** [comment]
Ok thx. Script works Fine now
