### ISSUE TITLE
Multiple clicks 

### ISSUE THREAD

**Issue by fllprbt** [DarkminecrafterHD/freebitco.in-Bot#8]
What if grid items refresh after click? You probably need to keep sending images...

**Comment by DarkminecrafterHD** [comment]
If your question is about the recaptchav2 resolving method, then that's not an issue.
we aint resolving recaptchav2 by sending pictures and getting numbers
we're solving then in interactive mode.

You can see the examples my code is based on here:
https://www.9kw.eu/grafik/plugins/9kweu_recaptcha_v2.zip
or check the entire iMacros page here:
https://www.9kw.eu/software_imacros.html

pls reply so we can know where's the issue or close it

thanks for your feedback

**Comment by fllprbt** [comment]
Sure, I will look throught it right now. But I checked your code and you had some comments as 'sending image to 9kw', 'getting text answer' etc.

**Comment by DarkminecrafterHD** [comment]
ohh
yes
that's because I merely hotfixed the code in the latest commit, so they are remainings of old code

Now the main issue is that the web is constanly changing the captcha types
So we may need to advance the port of the project to JavaScript

**Comment by fllprbt** [comment]
Oh please reply to your youtube acc I've send you a message

**Comment by fllprbt** [comment]
Right you were, issue closed.
